### ISSUE TITLE
Adding a licence

### ISSUE THREAD

**Issue by qnm** [blaztriglav/did-i#3]
Hi!

This looks cool. I found the repo via HN.

Would you mind adding a licence, please? I'd like to include it in [F-Droid](http://f-droid.org/)
- Rob

**Comment by blaztriglav** [comment]
Hey!

I've added the MIT license to the project and I've added license descriptions for the libraries used.

I looked into uploading to F-Droid myself, but it seems a bit more involved than I expected, so be my guest. Anything else you need? Anything I need to keep an eye out in terms of updating the app so I don't mess up the F-Droid packaging process? There's some donation metadata that can be added as well, how do I go about that?

Thanks for the help!

**Comment by dalb8** [comment]
The donation can be any http url: if it's paypal youre using don't give us the url of a javascript button, rather a url with your email address inside, or better, a dedicated download page explaining that you won't spend it  on cheap cider. Separate Flattr and Bitcoin is welcome too.

**Comment by dalb8** [comment]
Thanks for adding the origin of the jars. However the links don't actually work, except for the first one. F-droid just takes authors at their word anyway .

**Comment by blaztriglav** [comment]
@dalb8 thanks for the info above. I've fixed the links now.

Don't have a dedicated page, but I do have a Bitcoin address: 1FU27EyocpFFhexjoakSe7Hxvf4jD2KmFh

Doesn't hurt to add it I guess :)

**Comment by dalb8** [comment]
There are problems with Ormlite building on ant. I searched and this came at the top https://groups.google.com/forum/?fromgroups#!topic/ormlite-android/rUVI0d-khKk

**Comment by blaztriglav** [comment]
I added a build.xml for ant now, and it seems to build OK on my end. Did you get an error trying to build it, or was it meant more as a general notice?

**Comment by dalb8** [comment]
"Blaž Triglav" notifications@github.com wrote:

> I added a build.xml for ant now, and it seems to build OK on my end.
> Did you get an error trying to build it, or was it meant more as a
> general notice?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/blaztriglav/did-i/issues/3#issuecomment-9439781

No, it's a build error. If you build with ant you should see it.

**Comment by blaztriglav** [comment]
I did build it through ant and got no error. Might be my build.xml isn't properly configured, so it didn't include the libraries, but the app works if I install it from that APK. I'll check it out later today, my phone battery died and I forgot my USB cable at home, so I can't test further.

**Comment by dalb8** [comment]
"Blaž Triglav" notifications@github.com wrote:

> I did build it through ant and got no error. Might be my build.xml
> isn't properly configured, so it didn't include the libraries, but the
> app works if I install it from that APK. I'll check it out later today,
> my phone battery died and I forgot my USB cable at home, so I can't
> test further.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/blaztriglav/did-i/issues/3#issuecomment-9441843

The only difference I can think of is the platform tools version. we are on v14, the most recent.

**Comment by blaztriglav** [comment]
Ant built it fine in when doing 'ant debug' but I got the error when trying 'ant release'.

Added explicit casts now, works here, so it should be good to go. Thanks for letting me know!

**Comment by dalb8** [comment]
Still got the same errors at 193a3f47d0

**Comment by blaztriglav** [comment]
I am using the following:
- platfrom-tools v. 14 
- Apache Ant(TM) version 1.8.2 compiled on December 3 2011

Using "ant release" with the above compiles successfully after the last commit. Are you also building with "ant release"?

And could you paste the errors, please? I really don't understand what's messing it up, and why it would work here and not there. Sorry for the multiple failed attempts, it's the first time I'm using ant so it's all new to me.

**Comment by dalb8** [comment]
I've tried release and debug

-compile:
    [javac] Compiling 14 source files to /home/gerry/dalb8s-fdroiddata/build/si.modrajagoda.didi/Did I/bin/classes
    [javac] /home/gerry/dalb8s-fdroiddata/build/si.modrajagoda.didi/Did I/src/si/modrajagoda/didi/database/DatabaseHelper.java:58: type parameters of <D>D cannot be determined; no unique maximal instance exists for type variable D with upper bounds com.j256.ormlite.dao.Dao<si.modrajagoda.didi.database.Habit,java.lang.Integer>,com.j256.ormlite.dao.Dao<T,?>
    [javac]             habitDao = getDao(Habit.class);
    [javac]                              ^
    [javac] /home/gerry/dalb8s-fdroiddata/build/si.modrajagoda.didi/Did I/src/si/modrajagoda/didi/database/DatabaseHelper.java:65: type parameters of <D>D cannot be determined; no unique maximal instance exists for type variable D with upper bounds com.j256.ormlite.dao.Dao<si.modrajagoda.didi.database.Day,java.lang.Integer>,com.j256.ormlite.dao.Dao<T,?>
    [javac]             dayDao = getDao(Day.class);
    [javac]                            ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] 2 errors

**Comment by blaztriglav** [comment]
Added explicit casts at the two lines, please let me know if it works now. And thanks for being patient!

**Comment by dalb8** [comment]
Sorry, still the same.

**Comment by blaztriglav** [comment]
I finally got around to posting the question on StackOverflow, since I'm out of ideas:

http://stackoverflow.com/questions/13101576/android-project-with-ormlite-fails-to-build-in-ant

Hopefully someone figures it out :).

**Comment by dalb8** [comment]
Thanks. Whatever the solution it will fix the (2nd) latest AnyMemo build which has the same problem. I will nuke the repo and try again when I get a chance: you never know...

**Comment by dalb8** [comment]
And Worktime. It seems to be a common enough problem with Ormlite.

   [javac] /home/gerry/dalb8s-fdroiddata/build/eu.vranckaert.worktime/1.1.9/android-app/src/eu/vranckaert/worktime/dao/generic/GenericDaoImpl.java:59: type parameters of <D>D cannot be determined; no unique maximal instance exists for type variable D with upper bounds com.j256.ormlite.dao.Dao<T,ID>,com.j256.ormlite.dao.Dao<T,?>
    [javac]             dao = helper.getDao(clazz);
    [javac]                                ^

**Comment by blaztriglav** [comment]
The StackOverflow question only got one response, and the commenter cloned the repo and was able to successfully build with ant release. Is it possible the issue is on your end? Right now, I have no clue what to try next on my end.

Also, if any of the other apps resolve their issue, could you please let me know? If one of them figures it out, we'll probably all be able to fix it in the same way.

**Comment by dalb8** [comment]
I can't see how it would be our problem. We are using platform tools 14, etc, no customizations. I'll try one more time and let you know if the situation changes.

**Comment by dalb8** [comment]
I have ant 1.8.2 from _Oct 23_ , on opensuse 12.1

**Comment by dalb8** [comment]
Same error on ant 1.8.0 from April 2010 on ubuntu

**Comment by blaztriglav** [comment]
My current ant release is also 1.8.2 (was Dec 2011 at the start of debugging this two weeks ago, is now May 23 2012). I've successfully built it with ant on 2 different Ubuntu machines and a Windows machine. Using OpenJDK on Ubuntu, Sun's JDK on Windows.

Damn bugs, always ruining the fun. Thanks for trying multiple times and with multiple setups on your end as well. At least I learned how to use ant in the process.

**Comment by dalb8** [comment]
Its worth mentioning the Java version. It seems to work on 1.7 but not on 1.6.

**Comment by dalb8** [comment]
Actually the problem is with certain versions on Java 1.6 (not just eclipse): https://bugs.eclipse.org/bugs/show_bug.cgi?id=98379

**Comment by blaztriglav** [comment]
Sorry for the late response to this, I finally found a minute of free time. I had to go back and figure out where we left off. 

Can you build it with the new Java versions? Or do I still need to fix the code?

My lack of programming skills is shining through here :).

**Comment by dalb8** [comment]
It builds with newer Java versions but I don't know if there's any way to fix it for the version of Java we have on our build server, sorry.

**Comment by blaztriglav** [comment]
Thanks for the info, is there any chance the build server Java gets updated in the near future?

**Comment by dalb8** [comment]
It's just a fairly up to date of openjdk6 from Debian testing/Ubuntu Precise. I'm not even sure what version of Java that corresponds to but I would have thought it was greater than 1.6.0_24, but apparently not.

**Comment by dalb8** [comment]
We made some temporary changes to the java package, so the app is available for download from f-droid now. I added a beta tag and called the licence Apache because of some of the library dependencies.

**Comment by blaztriglav** [comment]
Awesome news! Thanks for the help.

**Comment by qnm** [comment]
Great work, both of you. Thanks for getting this added.
